### ISSUE TITLE
高架下の芝点群の誤検出

### ISSUE THREAD

**Issue by YoshitakaNagai** [amslabtech/road_recognizer#6]
地面タイルの色がまばらに異なる範囲が広く分布するせいで芝点群の誤検出が減らない

**Comment by YoshitakaNagai** [comment]
分散の計算を修正したら直った

**Comment by YoshitakaNagai** [comment]
確認走行区間のタイルの隙間の芝（ゴミ）点群もかなり減った

**Comment by ykuroda513** [comment]
言葉だけでなく，画像とか，グラフとかを載せてくれると理解しやすいし，あとから見ても何を話していたのかすぐわかるし，より意味のある議論ができると思います．
